# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MemeFeedV2' do
    pod 'Firebase/Core', '~> 5.15.0'
    pod 'Firebase/Auth', '~> 5.15.0'
    pod 'Firebase/Firestore', '~> 5.15.0'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end

